<?php

namespace ad\ClassifiedBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * attributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class attributeRepository extends EntityRepository
{
	/**
	 * Get attribute by name.
	 *
	 * @return attribute()
	 */
	public function findByName($name)
	{
		$em = $this->getEntityManager();
	
		$qb = $em->createQueryBuilder();
		$qb->addSelect('attr');
		$qb->from('adClassifiedBundle:attribute','attr');
		$qb->where('attr.name = :name');
	
		$qb->setParameter('name', $name);
		
		return $response = $qb->getQuery()->getResult();
	}
	
	
	
	
}
