<?php

namespace ad\ClassifiedBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * attributeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class attributeRepository extends EntityRepository
{
}
