<?php

namespace ad\ClassifiedBundle\Entity\Repository;

use Gedmo\Tree\Entity\Repository\NestedTreeRepository;
use ad\ClassifiedBundle\Entity\Category;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends NestedTreeRepository
{
	public function getCategory()
	{
		$em = $this->getEntityManager();

		$qb = $em->createQueryBuilder();
		$qb->addSelect('c');
		$qb->from('adClassifiedBundle:Category','c');
		$qb->where('c.parent is null');
		
		$response = $qb->getQuery()->getResult();
		
		$category = array();

		foreach ($response as $cat)
		{
			$category[]= $cat->setChildren(self::getChildren($cat));
		}
		
		return $category;
	}

	
}
