<?php

namespace ad\ClassifiedBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function getCategory()
	{
		$em = $this->getEntityManager();

		$qb = $em->createQueryBuilder();
		$qb->addSelect('c');
		$qb->from('adClassifiedBundle:Category','c');
		$qb->where('c.parent is null');
		
		$response = $qb->getQuery()->getResult();

		var_dump($response[0]);
		die;
		
		$category = array();

		foreach ($response as $cat)
		{
			$category[]= $cat->setChildren(self::getChildren($cat));
		}
		
		return $category;
	}

	public function getChildren($cat)
	{
		//var_dump($cat);
		//die;
		
		$em = $this->getEntityManager();

		$qb = $em->createQueryBuilder();
		$qb->addSelect('c');
		$qb->from('adClassifiedBundle:Category','c');
		$qb->where('c.parent = :parents');

		$qb->setParameter('parents', $cat->getParent());

		//var_dump($qb->getQuery()->getResult());
		//die;
		
		return $response = $qb->getQuery()->getResult();
	}
}
