<?php

namespace ad\ClassifiedBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * configRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class configRepository extends EntityRepository
{
	public function getConfig()
	{
		$em = $this->getEntityManager();
	
		$qb = $em->createQueryBuilder();
		$qb->addSelect('c');
		$qb->from('adClassifiedBundle:config','c');
	
		$response = $qb->getQuery()->getResult();
		
		return $response[0];
	}
}
