<?php

namespace ad\ClassifiedBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function getCategory()
	{
		$em = $this->getEntityManager();
		
		$qb = $em->createQueryBuilder();
		$qb->addSelect('c');
		$qb->from('adClassifiedBundle:Category','c');
		$qb->where('c.parentId = 1');
		
		$response = $qb->getQuery()->getResult();

		$category = array();		
		
		foreach ($response as $obj)
		{
			$category[]= $obj->setChildren(self::getChildren($obj));
		}
		
		//var_dump($category);
		//die;
		
		return $category;
	}
	
	public function getChildren($cat)
	{
		$em = $this->getEntityManager();
		
		$qb = $em->createQueryBuilder();
		$qb->addSelect('c');
		$qb->from('adClassifiedBundle:Category','c');
		$qb->where('c.parentId = :id');
		
		$qb->setParameter('id', $cat->getId());
		
		return $response = $qb->getQuery()->getResult();	
	}
}
