<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130528123618 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE attribute (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("CREATE TABLE attributeValues (id INT AUTO_INCREMENT NOT NULL, attribute_id INT NOT NULL, value VARCHAR(255) NOT NULL, Ads_id INT NOT NULL, INDEX IDX_540B46FAB6E62EFA (attribute_id), INDEX IDX_540B46FAF9FEBAB7 (Ads_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE attributeValues ADD CONSTRAINT FK_540B46FAB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id)");
        $this->addSql("ALTER TABLE attributeValues ADD CONSTRAINT FK_540B46FAF9FEBAB7 FOREIGN KEY (Ads_id) REFERENCES Ads (id)");
        $this->addSql("ALTER TABLE ads DROP owner_type, DROP owner_adress, DROP owner_city, DROP owner_zip, DROP owner_country, DROP owner_phone, DROP comment, DROP boat_id, DROP price, DROP confirmed, CHANGE title title VARCHAR(200) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE attributeValues DROP FOREIGN KEY FK_540B46FAB6E62EFA");
        $this->addSql("DROP TABLE attribute");
        $this->addSql("DROP TABLE attributeValues");
        $this->addSql("ALTER TABLE Ads ADD owner_type VARCHAR(42) NOT NULL, ADD owner_adress VARCHAR(255) NOT NULL, ADD owner_city VARCHAR(42) NOT NULL, ADD owner_zip INT NOT NULL, ADD owner_country VARCHAR(42) NOT NULL, ADD owner_phone INT NOT NULL, ADD comment LONGTEXT NOT NULL, ADD boat_id INT NOT NULL, ADD price INT NOT NULL, ADD confirmed INT DEFAULT NULL, CHANGE title title VARCHAR(42) NOT NULL");
    }
}
