<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130517141438 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("CREATE TABLE Ads (id INT AUTO_INCREMENT NOT NULL, owner_name VARCHAR(42) NOT NULL, owner_type VARCHAR(42) NOT NULL, owner_adress VARCHAR(255) NOT NULL, owner_city VARCHAR(42) NOT NULL, owner_zip INT NOT NULL, owner_country VARCHAR(42) NOT NULL, owner_phone INT NOT NULL, owner_comment LONGTEXT NOT NULL, boat_id INT NOT NULL, category_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
        $this->addSql("ALTER TABLE category CHANGE parent_id parent_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE category ADD CONSTRAINT FK_FF3A7B97727ACA70 FOREIGN KEY (parent_id) REFERENCES Category (id) ON DELETE CASCADE");
        $this->addSql("CREATE INDEX IDX_FF3A7B97727ACA70 ON category (parent_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("DROP TABLE Ads");
        $this->addSql("ALTER TABLE Category DROP FOREIGN KEY FK_FF3A7B97727ACA70");
        $this->addSql("DROP INDEX IDX_FF3A7B97727ACA70 ON Category");
        $this->addSql("ALTER TABLE Category CHANGE parent_id parent_id INT NOT NULL");
    }
}
