<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130523131827 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ads ADD CONSTRAINT FK_4684B0C012469DE2 FOREIGN KEY (category_id) REFERENCES Category (id)");
        $this->addSql("ALTER TABLE ads ADD CONSTRAINT FK_4684B0C0A76ED395 FOREIGN KEY (user_id) REFERENCES User (id)");
        $this->addSql("CREATE INDEX IDX_4684B0C012469DE2 ON ads (category_id)");
        $this->addSql("CREATE INDEX IDX_4684B0C0A76ED395 ON ads (user_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Ads DROP FOREIGN KEY FK_4684B0C012469DE2");
        $this->addSql("ALTER TABLE Ads DROP FOREIGN KEY FK_4684B0C0A76ED395");
        $this->addSql("DROP INDEX IDX_4684B0C012469DE2 ON Ads");
        $this->addSql("DROP INDEX IDX_4684B0C0A76ED395 ON Ads");
    }
}
