<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130606133020 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE ads DROP FOREIGN KEY FK_4684B0C012469DE2");
        $this->addSql("ALTER TABLE ads DROP FOREIGN KEY FK_4684B0C0A76ED395");
        $this->addSql("ALTER TABLE ads ADD date DATETIME NOT NULL");
        $this->addSql("ALTER TABLE ads ADD CONSTRAINT FK_4684B0C012469DE2 FOREIGN KEY (category_id) REFERENCES Category (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE ads ADD CONSTRAINT FK_4684B0C0A76ED395 FOREIGN KEY (user_id) REFERENCES User (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE attributevalues DROP FOREIGN KEY FK_540B46FAB6E62EFA");
        $this->addSql("ALTER TABLE attributevalues DROP FOREIGN KEY FK_540B46FAF9FEBAB7");
        $this->addSql("ALTER TABLE attributevalues ADD CONSTRAINT FK_540B46FAB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE attributevalues ADD CONSTRAINT FK_540B46FAF9FEBAB7 FOREIGN KEY (Ads_id) REFERENCES Ads (id) ON DELETE CASCADE");
        $this->addSql("ALTER TABLE category CHANGE slug slug VARCHAR(128) NOT NULL");
        $this->addSql("CREATE UNIQUE INDEX UNIQ_FF3A7B97989D9B62 ON category (slug)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Ads DROP FOREIGN KEY FK_4684B0C012469DE2");
        $this->addSql("ALTER TABLE Ads DROP FOREIGN KEY FK_4684B0C0A76ED395");
        $this->addSql("ALTER TABLE Ads DROP date");
        $this->addSql("ALTER TABLE Ads ADD CONSTRAINT FK_4684B0C012469DE2 FOREIGN KEY (category_id) REFERENCES category (id)");
        $this->addSql("ALTER TABLE Ads ADD CONSTRAINT FK_4684B0C0A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)");
        $this->addSql("ALTER TABLE attributeValues DROP FOREIGN KEY FK_540B46FAB6E62EFA");
        $this->addSql("ALTER TABLE attributeValues DROP FOREIGN KEY FK_540B46FAF9FEBAB7");
        $this->addSql("ALTER TABLE attributeValues ADD CONSTRAINT FK_540B46FAB6E62EFA FOREIGN KEY (attribute_id) REFERENCES attribute (id)");
        $this->addSql("ALTER TABLE attributeValues ADD CONSTRAINT FK_540B46FAF9FEBAB7 FOREIGN KEY (Ads_id) REFERENCES ads (id)");
        $this->addSql("DROP INDEX UNIQ_FF3A7B97989D9B62 ON Category");
        $this->addSql("ALTER TABLE Category CHANGE slug slug VARCHAR(42) NOT NULL");
    }
}
